#! /bin/sh
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
        if [ -n "$2" ]; then
            _dh_action=restart
        else
            _dh_action=start
            systemctl --system enable 'gtpd.socket' >/dev/null || true
        fi
        systemctl --system $_dh_action 'gtpd.socket' >/dev/null || true
    fi
fi
